-- AlterTable
ALTER TABLE `blog` ADD COLUMN `numberOfComments` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfLikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfSaves` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfShares` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `post` ADD COLUMN `numberOfComments` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfLikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfSaves` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfShares` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `numberOfSaves` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `vlog` ADD COLUMN `numberOfComments` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfLikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfSaves` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `numberOfShares` INTEGER NOT NULL DEFAULT 0;
